-- ============================================
-- KKOOKK Database Initialization Script
-- ============================================
-- This script runs automatically when the MySQL container is first created.
-- It grants necessary permissions to the application user.

-- Grant all privileges on kkookkdb to the application user
-- Note: MYSQL_USER is automatically created by MySQL Docker image
-- with access to MYSQL_DATABASE, but we ensure explicit grants here.

-- ============================================
-- Schema Definition
-- ============================================
-- Add your domain table definitions below.
-- Example:
--
-- CREATE TABLE IF NOT EXISTS example_table (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY,
--     name VARCHAR(255) NOT NULL,
--     created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
